#!/bin/dash

# colors

black=#3B4252
green=#D89079
white=#BBC3D4
grey=#373d49
blue=#81A1C1
darkblue=#7292b2
magenta=#C895BF
red=#BF616A
yellow=#F0D399


cyan_base='#8FBCBB'
cyan_bright='#93CCDC'
cyan_dim='#69A7BA'

red_base='#BF616A'
red_bright='#D06F79'
red_dim='#A54E56'

orange_base='#D08770'
orange_bright='#D89079'
orange_dim='#B46950'

yellow_base='#EBCB8B'
yellow_bright='#F0D399'
yellow_dim='#D9B263'

green_base='#A3BE8C'
green_bright='#B1D196'
green_dim='#8AA872'

magenta_base='#B48EAD'
magenta_bright='#C895BF'
magenta_dim='#9D7495'
